### ISSUE TITLE
Exception 0xC0000005 [STATUS_ACCESS_VIOLATION]

### ISSUE THREAD

**Issue by magiblot** [jpsdr/NNEDI3#5]
From version 0.9.4.39 on, running the follwing script causes the mentioned exception to occur:
(The script does not necessarily do anything useful)

> vint = AVISource("Bomberman Earthquake OVA.avi", audio=true) #YUY2 Source
> vint = vint.trim(716,0)
> vint
> AssumeTFF()
> SeparateFields()
> #ShowFrameNumber(scroll=true)
> separated = last
> #PointResize(Width(), Height()*2)
> f0 = separated.SelectEvery(5,0,1).Weave()
> f1 = separated.SelectEvery(5,3,4).Weave()
> Interleave(f0,f1)
> f0
> trim(5210,5222)
> sanimebob(1,usedaa3mod=true) #uses QTGMC 3.357s, which uses NNEDI3
> srestore(12.000/1.001)

AVSMeter reported the exception was caused by module NNEDI3.
I'm using AviSynth+ 0.1 (r2455, MT, i386), with x86/Release_W7 of NEEDI3.
It seems like version 0.9.4.38 won't crash.

**Comment by jpsdr** [comment]
What is the resolution of your video ? It seems that sanimebob is using a looooot of filters/plugins i don't have, so i'll not be able to run your script. I'll have to see if i can reproduce it just with nnedi3 alone, and not within ultra complex scripts which use nnedi3 i unfortunately don't understand realy how...
If, on your side, you can reproduce the issue with a simple script using just nnedi3, it will greatly help. Otherwise, it will probably just get to a dead end if i can't simply reproduce the issue...

**Comment by magiblot** [comment]
I'll try to isolate the problem when I have more time! :)
My source video is 720x480 interlaced, NTSC (it's in lossless format, uncomfortable to share).
I have splitted a short sample, however: http://tinyurl.com/khargod
I'm sorry to have you doing the dirty work, but here is a pack of dependencies for the new QTGMC: https://forum.doom9.org/showthread.php?p=1806162#post1806162
It should cover most of sanimebob dependencies, too.

**Comment by jpsdr** [comment]
Is it what you are using [https://pastebin.com/wZc8W13u](url) ?

**Comment by jpsdr** [comment]
I think i've found out. Great help telling me that .38 worked but not .39, it allowed me to quickly find out.

**Comment by magiblot** [comment]
> Is it what you are using https://pastebin.com/wZc8W13u ?
Yes, it is.

> I think i've found out. Great help telling me that .38 worked but not .39, it allowed me to quickly find out.

That's great! Thanks for the help.

**Comment by magiblot** [comment]
It doesn't crash anymore! ^^

**Comment by jpsdr** [comment]
Good.
