### ISSUE TITLE
Heavy artefacts when using QTGMC with NNEDI3 v0.9.4.54

### ISSUE THREAD

**Issue by MaxKoll** [jpsdr/NNEDI3#8]
Hi!

When using QTGMC (v3.364) with the most recent release of NNEDI3 (v0.9.4.54) I get very poor results. Strange artefacts appear, parts of the image shift and flicker. Also, QTGMC will output only every other frame, i. e. I get a double-fps video that runs at double speed and ends half way, with the second half filled up with black frames.

But, every other version of NNEDI3 works flawlessly. Perfect image and full-length double-fps video as expected.

Please compare the two [example videos](https://github.com/jpsdr/NNEDI3/files/4576955/examples.zip) (fps adjusted).

I'm afraid I don't know if this is actually a problem of NNEDI3 or QTGMC, but I felt I had to bring it to your attention.

Max

**Comment by jpsdr** [comment]
Unable to use QTGMC 3.364, allways error saying **AvsPlusVersionNumber** is unknow, despite having SMDegrain.avsi v3.1.2.106s in my plugin directory (i'm using avs+ 3.5.2).

**Comment by MaxKoll** [comment]
Yes, I struggled with this, too, until I found out that some shared functions have been removed from both QTGMC and SMDegrain, and a dedicated shared function library is needed: [Zs_RF_Shared.avsi](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/Zs_RF_Shared.avsi)

**Comment by jpsdr** [comment]
Just opened the following script in VDub
ColorBars(width=640, height=480, pixel_type="yv12")
QTGMC()

Didn't see anything, and fps is 59.94 (i assume it's expected...).

**Comment by jpsdr** [comment]
Then, i've tested with:
QTGMC(preset="Very Slow", InputType=0,sourceMatch=3, sharpness=0.2, tr2=2, ediThreads=8).SelectEven()

First it didn't work because i didn't have FFT3Dfilter, and i strugglde again to get libff3w... Finaly, i found a very recent (vv3.3.7) build on doom9.
Finaly i've been able to open the script with VDub, having an avisynth crash. It seems that when FFT3DFilter is involved, it's not good.
What is your script ? I've not been able to reproduce artefact issue, for now, i have an all or nothing situation.

**Comment by jpsdr** [comment]
Ok, finaly it was an issue within nnedi3, tell me if it's working properly with the new release.

**Comment by MaxKoll** [comment]
> What's your script ?

With NNEDI3 v0.9.4.54 I can reproduce the issue with just:
```
MPEG2Source([...])
QTGMC()
```

<br>

> Ok, finaly it was an issue within nnedi3, tell me if it's working properly with the new release.

Yes! v0.9.4.55 is working fine, thank you. :-)

**Comment by jpsdr** [comment]
Nice.
